CREATE SCHEMA IF NOT EXISTS `envilink-stg-data-platform`.`standardized__nasa` OPTIONS(location="asia-southeast1");

CREATE TABLE IF NOT EXISTS `envilink-stg-data-platform`.`standardized__nasa`.`viirs`
(
    hotspotid            STRING,
    feature_id           STRING,
    geometry             GEOGRAPHY,
    _createdAt           TIMESTAMP,
    _updatedAt           TIMESTAMP,
    _createdBy           STRING,
    _updatedBy           STRING,
    _id                  STRING,
    acquired_date        DATE,
    acquired_time        TIME,
    timestamp            INT64 OPTIONS(description="Epoch timestamp"),
    thai_date            DATE,
    thai_time            TIME,
    latitude             FLOAT64,
    longitude            FLOAT64,
    bright_ti4           FLOAT64,
    bright_ti5           FLOAT64,
    frp                  FLOAT64,
    scan                 FLOAT64,
    track                FLOAT64,
    confidence           STRING,
    instrument           STRING,
    satellite            STRING,
    version              STRING,
    file_name            STRING,
    ct_en                STRING,
    ct_tn                STRING,
    amphoe               STRING,
    amphoe_t             STRING,
    tambol               STRING,
    tambon_t             STRING,
    changwat             STRING,
    province_t           STRING,
    village              STRING,
    moo_1                STRING,
    name_1               STRING,
    linkgmap             STRING,
    ap_idn               INT64,
    pv_idn               INT64,
    tb_idn               INT64,
    ap_code              STRING,
    pv_code              STRING,
    tb_code              STRING,
    ap_en                STRING,
    ap_tn                STRING,
    pv_en                STRING,
    pv_tn                STRING,
    tb_en                STRING,
    tb_tn                STRING,
    lu_code              INT64,
    lu_hp                STRING,
    lu_hp_name           STRING,
    lu_name              STRING,
    f_alarm              INT64,
    utm_e                FLOAT64,
    utm_n                FLOAT64,
    utm_zone             STRING,
    v_angle              FLOAT64,
    v_direct             STRING,
    v_dist               FLOAT64,
    re_nesdb             STRING,
    re_royin             STRING,
    data_date            DATE,
    load_timestamp       TIMESTAMP
)
PARTITION BY data_date
OPTIONS(
  require_partition_filter=true,
  description="Full VIIRS hotspot data with geometry and admin details");
