CREATE NAMESPACE IF NOT EXISTS biglake.discovery__nasa;

CREATE TABLE IF NOT EXISTS biglake.discovery__nasa.viirs
(
    geometry             STRING COMMENT 'Geometry in WKT format (Point)',
    feature_id           STRING COMMENT 'Root feature ID',
    _createdAt           STRING,
    _createdBy           STRING,
    _id                  STRING,
    _updatedAt           STRING,
    _updatedBy           STRING,
    acq_date             STRING,
    acq_time             STRING,
    timestamp            STRING,
    th_date              STRING,
    th_time              STRING,
    hotspotid            STRING,
    file_name            STRING,
    latitude             STRING,
    longitude            STRING,
    bright_ti4           STRING,
    bright_ti5           STRING,
    frp                  STRING,
    confidence           STRING,
    scan                 STRING,
    track                STRING,
    instrument           STRING,
    satellite            STRING,
    version              STRING,
    ct_en                STRING,
    ct_tn                STRING,
    amphoe               STRING,
    amphoe_t             STRING,
    ap_code              STRING,
    ap_en                STRING,
    ap_idn               STRING,
    ap_tn                STRING,
    changwat             STRING,
    province_t           STRING,
    pv_code              STRING,
    pv_en                STRING,
    pv_idn               STRING,
    pv_tn                STRING,
    tambol               STRING,
    tambon_t             STRING,
    tb_code              STRING,
    tb_en                STRING,
    tb_idn               STRING,
    tb_tn                STRING,
    village              STRING,
    moo_1                STRING,
    name_1               STRING,
    linkgmap             STRING,
    re_nesdb             STRING,
    re_royin             STRING,
    f_alarm              STRING,
    lu_code              STRING,
    lu_hp                STRING,
    lu_hp_name           STRING,
    lu_name              STRING,
    utm_e                STRING,
    utm_n                STRING,
    utm_zone             STRING,
    v_angle              STRING,
    v_direct             STRING,
    v_dist               STRING,
    data_date            DATE COMMENT 'Partition date',
    load_timestamp       TIMESTAMP COMMENT 'Load timestamp'
)
USING iceberg
PARTITIONED BY (data_date)
LOCATION 'gs://envilink-asia-southeast1-stg-discovery/viirs'
TBLPROPERTIES ('comment' = 'Raw VIIRS hotspot data with all columns preserved.');
