CREATE NAMESPACE IF NOT EXISTS biglake.discovery;

CREATE TABLE IF NOT EXISTS biglake.discovery.dustboy
(
    id                   STRING,
    dustboy_id           STRING,
    dustboy_project      STRING,
    dustboy_uri          STRING,
    dustboy_name         STRING,
    dustboy_name_en      STRING,
    dustboy_lat          STRING,
    dustboy_lon          STRING,
    pm10                 STRING,
    pm25                 STRING,
    wind_speed           STRING,
    wind_direction       STRING,
    atmospheric          STRING,
    pm10_th_aqi          STRING,
    pm10_us_aqi          STRING,
    pm25_th_aqi          STRING,
    pm25_us_aqi          STRING,
    temp                 STRING,
    humid                STRING,
    us_aqi               STRING,
    us_color             STRING,
    us_dustboy_icon      STRING,
    us_title             STRING,
    us_title_en          STRING,
    us_caption           STRING,
    us_caption_en        STRING,
    th_aqi               STRING,
    th_color             STRING,
    th_dustboy_icon      STRING,
    th_title             STRING,
    th_title_en          STRING,
    th_caption           STRING,
    th_caption_en        STRING,
    daily_pm10           STRING,
    daily_pm10_th_aqi    STRING,
    daily_pm10_us_aqi    STRING,
    daily_pm25           STRING,
    daily_pm25_th_aqi    STRING,
    daily_pm25_us_aqi    STRING,
    daily_th_title       STRING,
    daily_th_title_en    STRING,
    daily_us_title       STRING,
    daily_us_title_en    STRING,
    daily_th_caption     STRING,
    daily_th_caption_en  STRING,
    daily_us_caption     STRING,
    daily_us_caption_en  STRING,
    daily_th_color       STRING,
    daily_us_color       STRING,
    daily_th_dustboy_icon STRING,
    daily_us_dustboy_icon STRING,
    daily_temp           STRING,
    daily_humid          STRING,
    daily_wind_speed     STRING,
    daily_wind_direction STRING,
    daily_atmospheric    STRING,
    province_id          STRING,
    log_datetime         STRING,
    data_date            DATE,
    load_timestamp       TIMESTAMP
)
USING iceberg
PARTITIONED BY (data_date)
LOCATION 'gs://envilink-asia-southeast1-stg-discovery/dustboy'
;
