CREATE SCHEMA IF NOT EXISTS `envilink-stg-data-platform`.`standardized` OPTIONS(location="asia-southeast1");

CREATE TABLE IF NOT EXISTS `envilink-stg-data-platform`.`standardized`.`dustboy`
(
    id                   STRING,
    dustboy_id           STRING,
    dustboy_project      STRING,
    dustboy_uri          STRING,
    dustboy_name         STRING,
    dustboy_name_en      STRING,
    dustboy_lat          FLOAT64,
    dustboy_lon          FLOAT64,
    pm10                 FLOAT64,
    pm25                 FLOAT64,
    wind_speed           FLOAT64,
    wind_direction       FLOAT64,
    atmospheric          FLOAT64,
    pm10_th_aqi          FLOAT64,
    pm10_us_aqi          FLOAT64,
    pm25_th_aqi          FLOAT64,
    pm25_us_aqi          FLOAT64,
    temp                 FLOAT64,
    humid                FLOAT64,
    us_aqi               FLOAT64,
    us_color             STRING,
    us_dustboy_icon      STRING,
    us_title             STRING,
    us_title_en          STRING,
    us_caption           STRING,
    us_caption_en        STRING,
    th_aqi               FLOAT64,
    th_color             STRING,
    th_dustboy_icon      STRING,
    th_title             STRING,
    th_title_en          STRING,
    th_caption           STRING,
    th_caption_en        STRING,
    daily_pm10           FLOAT64,
    daily_pm10_th_aqi    FLOAT64,
    daily_pm10_us_aqi    FLOAT64,
    daily_pm25           FLOAT64,
    daily_pm25_th_aqi    FLOAT64,
    daily_pm25_us_aqi    FLOAT64,
    daily_th_title       STRING,
    daily_th_title_en    STRING,
    daily_us_title       STRING,
    daily_us_title_en    STRING,
    daily_th_caption     STRING,
    daily_th_caption_en  STRING,
    daily_us_caption     STRING,
    daily_us_caption_en  STRING,
    daily_th_color       STRING,
    daily_us_color       STRING,
    daily_th_dustboy_icon STRING,
    daily_us_dustboy_icon STRING,
    daily_temp           FLOAT64,
    daily_humid          FLOAT64,
    daily_wind_speed     FLOAT64,
    daily_wind_direction FLOAT64,
    daily_atmospheric    FLOAT64,
    province_id          STRING,
    log_datetime         TIMESTAMP,
    data_date            DATE,
    load_timestamp       TIMESTAMP
)
PARTITION BY data_date
OPTIONS(
  require_partition_filter=true);
