CREATE SCHEMA IF NOT EXISTS `envilink-stg-data-platform`.`standardized` OPTIONS(location="asia-southeast1");

CREATE TABLE IF NOT EXISTS `envilink-stg-data-platform`.`standardized`.`viirs_geojson_bq`
(
    feature_id           STRING,
    geometry             GEOGRAPHY,
    hotspot_id           STRING,
    acquisition_date     DATE,
    acquisition_time     TIME,
    thai_date            DATE,
    thai_time            TIME,
    brightness_ti4       FLOAT64,
    brightness_ti5       FLOAT64,
    fire_radiative_power FLOAT64,
    confidence           STRING,
    instrument           STRING,
    satellite            STRING,
    file_name            STRING,
    scan                 FLOAT64,
    track                FLOAT64,
    version              STRING,
    timestamp            INT64,
    fire_alarm           INT64,
    view_angle           FLOAT64,
    view_direction       STRING,
    view_distance        FLOAT64,
    latitude             FLOAT64,
    longitude            FLOAT64,
    utm_east             FLOAT64,
    utm_north            FLOAT64,
    utm_zone             STRING,
    country_en           STRING,
    country_tn           STRING,
    changwat             STRING,
    province_code        STRING,
    province_en          STRING,
    province_idn         INT64,
    province_tn          STRING,
    province_t           STRING,
    amphoe               STRING,
    amphoe_t             STRING,
    amphoe_code          STRING,
    amphoe_en            STRING,
    amphoe_idn           INT64,
    amphoe_tn            STRING,
    tambol               STRING,
    tambon_t             STRING,
    tambon_code          STRING,
    tambon_en            STRING,
    tambon_idn           INT64,
    tambon_tn            STRING,
    village              STRING,
    moo                  STRING,
    name                 STRING,
    land_use_code        INT64,
    land_use_hp          STRING,
    land_use_hp_name     STRING,
    land_use_name        STRING,
    reference_nesdb      STRING,
    reference_royin      STRING,
    link_gmap            STRING,
    record_id            STRING,
    created_at           STRING,
    created_by           STRING,
    updated_at           STRING,
    updated_by           STRING,
    data_date            DATE,
    load_timestamp       TIMESTAMP
)
PARTITION BY data_date
OPTIONS(
  require_partition_filter=true);
